<a href="https://colab.research.google.com/github/geocarvalho/python-ds/blob/master/MLmastering/linear_algebra_for_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [Basics for linear algebra for ML - Discover the mathematical language of data in python - Jason Bownlee](https://machinelearningmastery.com/linear_algebra_for_machine_learning/)

## Chapter 4 - Introduction to Numpy arrays

In [0]:
import numpy as np

# Create array
l = [1.0, 2.0, 3.0]x
a = np.array(l)

# Display array
print(a)

# Display array shape
print(a.shape)

# Display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


### Creating arrays

* An empty array with aleatory numbers with `empty()`;
* An array with zeros using `zeros()`;
* An array with ones using `ones()`

In [0]:
# Create empty array
a = np.empty([3,3])
print(a)

[[3.84564651e-316 2.07507571e-322 2.12199579e-314]
 [3.44620186e-085 4.34900767e+199 1.87422380e+261]
 [1.43622020e+161 3.27748089e+180 1.27014396e-319]]


In [0]:
# Create zero array
a = np.zeros([3, 5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [0]:
# Create one array
a = np.ones([2,5])
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Combining arrays

* Vertical Stack with `vstack()`
* Horizontal Stack with `hstack()`

In [0]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(a1)
print(a2)

[1 2 3]
[4 5 6]


In [0]:
a3 = np.vstack((a1, a2))
print(a3)
print(a3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [0]:
a4 = np.hstack((a1, a2))
print(a4)
print(a4.shape)

[1 2 3 4 5 6]
(6,)


## Chapter 5 - Index, slice and reshape Numpy arrays

### From list to arrays

* One-dimensional list to array
* Two-dimensional list of lists to array

In [0]:
# Create one-dimensional array
data1 = [11, 22, 33, 44, 55]

# Array of data
data1 = np.array(data1)
data1

array([11, 22, 33, 44, 55])

In [0]:
# Create two-dimensional array
data2 = [[11, 22],
        [33, 44],
        [55, 66]]

# Array of data
data2 = np.array(data2)
data2

array([[11, 22],
       [33, 44],
       [55, 66]])

### Array indexing
* One-dimensional indexing
* Two-dimensional indexing

In [0]:
# One-dimensional
print(data1[0])
print(data1[-1])

11
55


In [0]:
# Two dimensional
print(data2[0,0])
print(data2[0,])

11
[11 22]


In [0]:
# Two dimensional like C-based languages
print(data2[0])
print(data2[0][0])

[11 22]
11


### Array slicing
* One-dimensional slicing
* Two-dimensional slicing

In [0]:
# One-dimensional
print(data1[:])
print(data1[0:1])
print(data1[-2:])

[11 22 33 44 55]
[11]
[44 55]


In [0]:
# Two-dimensional
print(data2[:, :-1])
print(data2[:, -1])

[[11]
 [33]
 [55]]
[22 44 66]


In [0]:
data = np.array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])

print(data[:, :-1])
print(data[:, -1])

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


### Array reshaping
* Reshape 1d to 2d array

In [0]:
data1.shape

(5,)

In [0]:
data2.shape

(3, 2)

In [0]:
print( ' Rows: %d ' % data2.shape[0])
print( ' Cols: %d ' % data2.shape[1])

 Rows: 3 
 Cols: 2 


In [0]:
# reshape 1D to 2D array
data = data1.reshape((data1.shape[0], 1))
data.shape

(5, 1)

In [0]:
data = data2.reshape((data2.shape[0], data2.shape[1], 1))
print(data)
print(data.shape)

[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]
(3, 2, 1)


## Chapter 6 - Numpy array broadcasting

* Duplicate the smaller array so that it has the dimensionality and size as the larger array.

### Limitation with array arithmetic


In [0]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
c = a + b
c

array([2, 4, 6])

### Broadcast scalar to one-dimensional array


In [0]:
a = np.array([1, 2, 3])
b = 2
c = a + b
c

array([3, 4, 5])

### Broadcast scalar to two-dimensional array

In [0]:
a = np.array([
[1, 2, 3],
[1, 2, 3]])
b = 2
c = a + b
c

array([[3, 4, 5],
       [3, 4, 5]])

### One-dimensional and two-dimensional arrays

In [0]:
a = np.array([
[1, 2, 3],
[1, 2, 3]])
b = np.array([1,2,3])
c = a + b
c

array([[2, 4, 6],
       [2, 4, 6]])

### Limitations

* Arithmetic, including broadcasting, can only be performed when the shape of each dimension in the arrays are equal or one has the dimension size of 1.

In [0]:
a = np.array([
[1, 2, 3],
[1, 2, 3]])
print(a.shape)
b = np.array([1,2])
print(b.shape)
c = a + b
print(c)

(2, 3)
(2,)


ValueError: ignored

## Chapter 7 - Vectors and vector arithmetic

* Vector is a tuple of one or more values called scalars

In [0]:
v = np.array([1,2,3])
v

In [0]:
a = np.array([1,2,3])
b = np.array([1,2,3])
c = a + b
c

In [0]:
d = a - b
d

In [0]:
e = a * b
e

In [0]:
f = a / b
f

### Vector dot product

* The sum of the multiplied elements of two vectors of the same length.

In [0]:
g = a.dot(b)
g

### Vector-scalar multiplication

* Multiply each element of the vector by a scalar, resulting in a new scaled vector of the same length

In [0]:
s = 0.5
s * a

## Chapter 8 - Vector Norms

* Vector norm is the calculation of vector lengths or magnitudes;

* $L^1$ norm is the sum of the absolute values of the vector;

* $L^2$ norm is the square root of the sum of the squared vector values;

* The $max$ norm is the maximum vector values.


### Vector norm (magnitude)

* The length of the vector is always a positive number, except for a vector of zeros as values;

* It's calculated using some measure that summarizes the distance of the vector from the origin of the vector space.

### Vector $L¹$ norm

* The notation of a vector is $||v||_1$, where 1 is a subcript;

* This length is sometimes called **the taxicab norm** or **the Manhattan norm**;

$L^1(v) = ||v||_1$

* It's calculated as the sum of the absolute vector values, where the absolute value of a scalar uses the notation $|a_1|$;

* The norm is a calculation of the Manhattan distance from the origin of the vector space

$||v||_1 = |a_1| + |a_2| + |a_3|$

* It can be calculated in Numpy using the `norm()` function with a paramater to specify the norm order (1 in this case)



In [0]:
a = np.array([1, 2, 3])
l1 = np.linalg.norm(a, 1)
l1

> The $L^1$ norm is often used when fitting ML algorithms as a regularization method. For example, a method to keep the coefficients of the model small and in turn, the model less complex.

### Vector $L^2$ norm

* The notation is $||v||_2$, where 2 is a subscript

$L^2(v) = ||v||_2$

* It calculates the distance of the vector coordinate from the origin of the vector space. Also know as **the Euclidean norm** as it's calculated as the Euclidean distance from the origin;

* It's calculated as the square root of the sum of the squared vector values;

$||v||_2 = \sqrt{a^2_1 + a^2_2 + a^2_3}$

* It can be calculated in Numpy using the `norm()` function with default parameters;

In [0]:
l2 = np.linalg.norm(a)
l2

> Like $L^1$ norm, $L^2$ norm is often used when fitting ML algorithms as a regularization method, but is more commonly used than other vector norms in ML. For example, a method to keep the coefficients of the model small and, in turn, the model less complex.

### Vector Max norm

* Referred as $L^{inf}$, the notation is $||v||_{inf}$;

$L^{inf}(v) = ||v||_{inf}$

* It's calculated as returning the maximum value of the vector;

$||v||_{inf} = \mathrm{max}a_1,a_2,a_3$

* It can be calculated in Numpy using the `norm()` function with the order parameter set to `inf`.

In [0]:
from math import inf

maxnorm = np.linalg.norm(a, inf)
maxnorm

> Max norm is also used as a regularization in ML, such as on NN weights, called max norm regularization.

---

## Chapter 9 - Matrices and matrix arithmetic

* Matrix is a two-dimensional array (a table) of numbers;

* The notation is often an uppercase letter, such as $A$, and entries are referred to by their two-dimensional subscript of row ($i$) and column ($j$), such as $a_{i,j}$;

$A = ((a_{1,1},a_{1,2}),(a_{2,1},a_{2,2}),(a_{3,1},a_{3,2}))$

* Often the dimensions of the matrix are denoted as $m$ and $n$ or $m \times n$ for the number of rows and the number of columns respectively.

### Defining a matrix

* In python we can represent a matrix using a two-dimensional Numpy array.


In [0]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
A

### Matrix arithmetic

* Some operations are performed element-wise between two matrices of equal size to result in a new matrix with the same size.

In [0]:
# Define first matrix
A = np.array([[1, 2, 3],
              [4, 5, 6]])
print(A)
# Define second matrix
B = np.array([[0.5, 0.5, 0.5],
              [0.5, 0.5, 0.5]])
print(B)


In [0]:
# Matrix addition
C = A + B
print(C)

In [0]:
# Matrix subtraction
D = A - B
print(D)

In [0]:
# Matrix multiplication (Hadamard product)
E = A * B
print(E)

In [0]:
# Matrix division
F = A / B
print(F)

In [0]:
# Matrix-matrix multiplication (matrix dot)

* In matrix-matrix multiplication, the number of columns ($n$) in the first matrix ($A$) must be equal the number of rows ($m$) in the second matrix ($B$)

$C(m,k) = A(m,n) \cdot B(n,k)$

* The matrix multiplication using matrix notation

$ A = \begin{pmatrix}
       a_{1,1} & a_{1,2} \\[0.3em]
       a_{2,1} & a_{2,2} \\[0.3em]
       a_{3,1} & a_{3,2} \end{pmatrix}$

$ B = \begin{pmatrix}
       b_{1,1} & b_{1,2} \\[0.3em]
       b_{2,1} & b_{2,2} \end{pmatrix}$

$ C = \begin{pmatrix}
       a_{1,1} \times b_{1,1} + a_{1,2} \times b_{2,1},a_{1,1} \times b_{1,2} + a_{1,2} \times b_{2,2} \\
       a_{2,1} \times b_{1,1} + a_{2,2} \times b_{2,1},a_{2,1} \times b_{1,2} + a_{2,2} \times b_{2,2} \\
       a_{3,1} \times b_{1,1} + a_{3,2} \times b_{2,1},a_{3,1} \times b_{1,2} + a_{3,2} \times b_{2,2} \\ \end{pmatrix}$
       
       

* It can be implemented in Numpy using the `dot()` function or with the `@` in python3.5.

In [0]:
# define first matrix
A = np.array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define second matrix
B = np.array([
[1, 2],
[3, 4]])
print(B)

In [0]:
# multiply matrices
C = A.dot(B)
print(C)
# multiply matrices with @ operator
D = A @ B
print(D)

### Matrix-vector multiplication

* The number of columns in the matrix must be equal the number of items in the vector;

* Because the vector only has one column, the result is always a vector;

$c = A \cdot v$

$ A = \begin{pmatrix}
       a_{1,1} & a_{1,2} \\[0.3em]
       a_{2,1} & a_{2,2} \\[0.3em]
       a_{3,1} & a_{3,2} \end{pmatrix}$

$ v = \begin{pmatrix}
       v_1 \\[0.3em]
       v_2 \end{pmatrix}$

$ c = \begin{pmatrix}
       a_{1,1} \times v_1 + a_{1,2} \times v_2 \\
       a_{2,1} \times v_1 + a_{2,2} \times v_2 \\
       a_{3,1} \times v_1 + a_{3,2} \times v_2 \\ \end{pmatrix}$
       

In [0]:
# matrix-vector multiplication
A = np.array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define vector
B = np.array([0.5, 0.5])
print(B)
# multiply
C = A.dot(B)
print(C)

### Matrix-scalar multiplication

$C = A \cdot b$

$ A = \begin{pmatrix}
       a_{1,1} & a_{1,2} \\[0.3em]
       a_{2,1} & a_{2,2} \\[0.3em]
       a_{3,1} & a_{3,2} \end{pmatrix}$

$ c = \begin{pmatrix}
       a_{1,1} \times b+ a_{1,2} \times b \\
       a_{2,1} \times b + a_{2,2} \times b \\
       a_{3,1} \times b + a_{3,2} \times b \\ \end{pmatrix}$

In [0]:
# matrix-scalar multiplication
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)
# define scalar
b = 0.5
print(b)
# multiply
C = A * b
print(C)

## Chapter 10 - Types of matrices

### Square matrix

* The number of rows($n$) is equivalent to the number of columns ($m$);

> The rectangular matrix has a different the number of rows and columns.

$ M = \begin{pmatrix}
       1 \space 2 \space 3 \\
       1 \space 2 \space 3 \\
       1 \space 2 \space 3 \\ \end{pmatrix}$

### Symmetric matrix

* Is a type of square matrix where the top-right triangle is the same as the bottom-left triangle;

$ M = \begin{pmatrix}
       1 \space 2 \space 3 \space 4 \space 5 \\
       2 \space 1 \space 2 \space 3 \space 4 \\
       3 \space 2 \space 1 \space 2 \space 3 \\
       4 \space 3 \space 2 \space 1 \space 2 \\
       5 \space 4 \space 3 \space 2 \space 1 \end{pmatrix}$

### Triangular matrix

* Is a type of square matrix that has all values in the upper-right or lower-left of the matrix with the remaining elements filled with zero values;

* Upper triangular matrix:

$ M = \begin{pmatrix}
       1 \space 2 \space 3 \\
       0 \space 2 \space 3 \\
       0 \space 0 \space 3 \\ \end{pmatrix}$

* Lower triangular matrix:

$ M = \begin{pmatrix}
       1 \space 0 \space 0 \\
       1 \space 2 \space 0 \\
       1 \space 2 \space 3 \\ \end{pmatrix}$


* Numpy has a function for lower triangular matrix (`tril`) and upper triangular matrix (`triu`).

In [0]:
M = np.array([[1,2,3],
              [1,2,3],
              [1,2,3]])
M

In [0]:
# lower triangular matrix
lower = np.tril(M)
print(lower)

In [0]:
# upper triangular matrix
upper = np.triu(M)
print(upper)

### Diagonal matrix

* Consist mostly of zeros and have non-zero entries only along the main diagonal;

$ D = \begin{pmatrix}
       1 \space 0 \space 0 \\
       0 \space 2 \space 0 \\
       0 \space 0 \space 3 \\
       0 \space 0 \space 0 \end{pmatrix}$

* As a vector:

$ D = \begin{pmatrix}
       d_{1,1} \\
       d_{2,2} \\
       d_{3,3} \\ \end{pmatrix}$

* Numpy provides the function *diag()* that can create a diagonal matrix from a existing matrix.

In [0]:
d = np.diag(M)
print(d)
D = np.diag(d)
print(D)


### Identity matrix

* Is a square that does not change a vector when multiplied;

* All of the scalar values along the main diagonal (top-left to bottom-right) have the value one, while all other values are zero;

$ I = \begin{pmatrix}
       1 \space 0 \space 0 \\
       0 \space 1 \space 0 \\
       0 \space 0 \space 1 \\ \end{pmatrix}$

* In Numpy we can use the `identity()` function

In [0]:
I = np.identity(3)
I

### Orthogonal matrix

* Two vectors are orthogonal when their dot product is equals zero;

* The length of each vector is 1 then the vectors are called orthonormal because they are both orthogonal and normalized;

$v \cdot w = 0$ or $v \cdot w^T=0$

* An orthogonal matrix is a type of square matrix whose columns and rows are orthonormal unit vectors;

> Perpendicular and have a length or magnitude of 1;

* The Orthogonal matrix is defined formally as:

$Q^T \cdot Q = Q \cdot Q^T = I$

> $Q$ is the orthogonal matrix, $Q^T$ is the transpose of $Q$, and $I$ is the identity matrix.

* A matrix is orthogonal if its transpose is equal to its inverse;

$Q^T = Q^{-1}$

* And if the dot product of the matrix and itself are equals the identity matrix;

$Q \cdot Q^T = I$

* Orthogonal matrices are used a lot for linear transformations, such as **reflections and permutations**;

* A simple 2x2 orthogonal matrix (reflection matrix or coordinate reflection):

$ Q = \begin{pmatrix}
       1 \space 0 \\
       0 \space -1 \end{pmatrix}$



* With Numpy we can create a orthogonal matrix and check the equivalences:

In [0]:
Q = np.array([[1,0],
              [0,-1]])
print(Q)
# Inverse equivalence
V = np.linalg.inv(Q)
print(Q.T)
print(V)
# Identity equivalence
I = Q.dot(Q.T)
print(I)


* Sometimes a number close to zero can be represented as $-0$ due to the rounding of floating point precision, just take it as $0.0$;

* Orthogonal matrices are useful tools as they are computanionally cheap and stable to calculate their inverse as simply their transpose.

---

## Chapter 11 - Matrix operations

### Transpose

* A matrix can be transposed, which creates a new matrix with the number of columns and rows flipped;

$C = A^T$

$ A = \begin{pmatrix}
       1 \space 2 \\
       3 \space 4 \\
       5 \space 6 \\ \end{pmatrix}$

$ A^T = \begin{pmatrix}
       1 \space 3 \space 5 \\
       2 \space 4 \space 6 \end{pmatrix}$

* We can transpose a matrix in Numpy using the **T** attribute.

In [0]:
A = np.array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# calculate transpose
C = A.T
print(C)


## Inverse

* Matrix inversion is a process that finds another matrix that when multiplied with the matrix, results in an identity matrix;

$AB = BA = I^n$

* The operation of iverting a matrix is indicated by a $-1$ superscript next to the matrix:

$B = A^{-1}$

* A matrix can be inverted in Numpy using the `inv` function:

In [0]:
A = np.array([[1.0, 2.0],
              [3.0, 4.0]])
print(A)
B = np.linalg.inv(A)
print(B)
I = A.dot(B)
print(I)

* Matrix inversion is used as an operation in solving systems of equations framed as matrix equations where we are interested in finding vectors of unknows;

* A good example is in finding the vector of coefficient values in linear regression.

### Trace

* Is the sum of the values on the main diagonal of the matrix (top-left to bottom-right);

* Alone, the trace operation is not interesting, but it offers a simpler notation and it is used as an element in other key matrix operations;

* Is described as the notation $tr(A)$:

$tr(A) = a_{1,1} + a_{2,2} + a_{3,3}$

* In Numpy we use the `trace()` function:

In [0]:
A = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# calculate trace
B = np.trace(A)
print(B)

## Determinant

* Is a scalar representation of the volume of the matrix;

* Denoted by the $det(A)$ or $|A|$;

* Is the product of all the **eigenvalues** of the matrix;

* It describes the way a matrix will scale another matrix when they are multiplied together;

> A determinant of 1 preserves the space of the other matrix, a determinant of 0 indicates that the matrix cannot be inverted.

* Like the **trace** operation, alone it is not interesting, but it offers a simpler notation and it is used as an element in other key matrix operations;

* In Numpy we use the `det()` function:

In [0]:
A = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# calculate determinant
B = np.linalg.det(A)
print(B)

## Rank

* The rank of a matrix is the estimate of the number of linearly independent rows or columns in a matrix;

* Denoted as $rank(A)$;

* An intuition for **rank** is to consider it the number of dimensions spanned by all of the vectors within a matrix;

> A **rank** of 0 suggest all vectors span a point, a **rank** of 1 suggests all vectors span a line, a rank of 2 suggest all vectors span a two-dimensional plan.

* It is estimated numerically, often using a matrix decomposition method. A common approach is to use the Singular-Value Decomposition (SVD);

* Numpy provides the `matrix_rank()` function, it used the SVD method to estimate the rank.

In [0]:
# rank
v1 = np.array([1,2,3])
print(v1)
vr1 = np.linalg.matrix_rank(v1)
print(vr1)
print()
# zero rank
v2 = np.array([0,0,0,0,0])
print(v2)
vr2 = np.linalg.matrix_rank(v2)
print(vr2)

* The next example makes it clear that the **rank** isn't the number of dimensions of the matrix, but the number of linearly independent directions:

In [0]:
# rank 0
M0 = np.array([
[0,0],
[0,0]])
print(M0)
mr0 = np.linalg.matrix_rank(M0)
print(mr0)
print()

# rank 1
M1 = np.array([
[1,2],
[1,2]])
print(M1)
mr1 = np.linalg.matrix_rank(M1)
print(mr1)
print()

# rank 2
M2 = np.array([
[1,2],
[3,4]])
print(M2)
mr2 = np.linalg.matrix_rank(M2)
print(mr2)

## Chapter 12 - Sparse matrices

* Matrices that *contain mostly zero values* are called **sparse**, distinct from matrices where most of the values are non-zero, called **dense**;

* Improvement in performance can be achieved by using representations and operations that specifically handle the matrix sparsity;

### Sparce matrix

* The sparsity of a matrix can be quantified with a score, which is the number of zero values in the matrix divided by the total number of elements in the matrix;

$sparcity = \frac{count \space of \space non-zero \space elements}{total \space elements}$

$ A = \begin{pmatrix}
       1 \space 0 \space 0 \space 1 \space 0 \space 0 \\
       0 \space 0 \space 2 \space 0 \space 0 \space 1 \\
       0 \space 0 \space 0 \space 2 \space 0 \space 0 \\ \end{pmatrix}$

> The example has 13 zero values of the 18 elements in the matrix, giving this matrix a sparsity score of 0.722 or about 72%.



#### a) space complexity

* Very large matrices require a lot of memory, and some very large matrices that we wish to work with are sparse.

#### b) time complexity

* Performe operations across this matrix may take a long time where the bulk of the computation performed will involve adding or multiplying zero values together;

### Sparce matrix in ML

#### a) data

* Sparce matrices come up in some specific types of data, most notably observations that record the occurrence or count of an activity.

#### b) data preparation

* Sparce matrices come up in encoding shemes used in the data preparation.

> One hot encoding, count encoding, TF-IDF encoding.

#### c) areas of study

* Some areas of study within ML must develop specialized methods to address sparsity directly as the input data is almost always sparse.

> Natural language processing, recommender systems, computer vision.

### Working with sparce matrices

* To work and represent sparce matrices we use a alternate structure where the zero values can be ignored and only the data or non-zero values need to be stored or acted upon.

 * **Dictionary of keys** : where a row and column index is mapped to a value;

 * **List of lists**: each row of the matrix is stored as a list, with each sublist containing the column index and the value;

 * **Coordinate list**: a list of tuples is stored with each tuple containing the row index, column index, and the value.

* There are data structures that are more suitable for performing efficient operations:

 * **Compressed sparse row (CSR)**: three one-dimensional arrays for the non-zero values, the extents of the rows, and the column indexes. *Commonly used in ML*;

 * **Compressed sparse column**: the same as the *compressed sparce row* method except the column indices are compressed and read first before the row indices.

### Sparce matrices in python

* A dense matrix stored in a numpy array can be converted into a sparse matrix using the CSR representation by calling the `csr_matrix()` function;

* In the example below, we define a 3x6 sparse matrix as a dense array, convert it to a CSR sparse represetation, and then convert it back to a dense array by calling the `todense()` function.

In [0]:
from scipy.sparse import csr_matrix

A = np.array([[1,0,0,1,0,0],
              [0,0,2,0,0,1],
              [0,0,0,2,0,0]])
print(A)

# convert to sparse matrix (CSR method)
S = csr_matrix(A)
print()
print(S)

# reconstruct dense matrix
B = S.todense()
print()
print(B)

* Numpy does not provide a function to calculate the sparsity of a matrix. Nevertheless, we can calculatr it finding the density of the matrix and subtracting it from one;

* The number of non-zero elements can be given by the `count_nonzero()` function and the total number of elements in the array can be given bu the size property of the array.

In [0]:
sparsity = 1.0 - np.count_nonzero(A) / A.size
print(sparsity)

## Chapter 13 - Tensor and tensor arithmetic

### What are tensors

* Is a generalization of vectors and matrices and is easily understood as a multidimensional array;

* A vector is a one-dimensional or first order tensor and a matrix is a two-dimensional or second order tensor;

* Below defines a $3 \times 3 \times 3$ three-dimensional tensor $T$ with dimensions index as $t_{i,j,k}$:

$ A = \begin{pmatrix}
       t_{1,1,1} \space t_{1,2,1} \space t_{1,3,1} \\
       t_{2,1,1} \space t_{2,2,1} \space t_{2,3,1} \\
       t_{3,1,1} \space t_{3,2,1} \space t_{3,3,1} \end{pmatrix} , \begin{pmatrix}
       t_{1,1,2} \space t_{1,2,2} \space t_{1,3,2} \\
       t_{2,1,2} \space t_{2,2,2} \space t_{2,3,2} \\
       t_{3,1,2} \space t_{3,2,2} \space t_{3,3,2} \end{pmatrix}, \begin{pmatrix}
       t_{1,1,3} \space t_{1,2,3} \space t_{1,3,3} \\
       t_{2,1,3} \space t_{2,2,3} \space t_{2,3,3} \\
       t_{3,1,3} \space t_{3,2,3} \space t_{3,3,3} \end{pmatrix}$

* Many of the operations that can be performed with *scalars*, *vectors*, and *matrices* can be reformulated to be performed with tensors.




### Tensors in python

* A tensor can be defined in-line to be a constructor of `array()` as a list of lists;

* We first define rows, then a list of rows stacked as columns, then a list of column stacked as levels in a cube.

In [0]:
# create a tensor
T = np.array([
              [[1,2,3], [4,5,6], [7,8,9]],
              [[11,12,13], [14,15,16], [17,18,19]],
              [[21,22,23], [24,25,26], [27,28,29]]
])
print(T.shape)
print(T)

### Tensor arithmetic

#### a) tensor addition

* The element-wise addition of two tensors with the same dimensions results in a new tensor with the same dimensions where each scalar value is the element-wise addition of the scalars in the parent tensors.

$C = A+B$

In [0]:
# define first tensor
A = np.array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
# define second tensor
B = np.array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
# add tensors
C = A + B
print("A = ", A)
print()
print("B = ", B)
print()
print("C = ", C)

#### b) tensor subtraction
* The element-wise substraction of one tensor from another tensor with the same dimensions results in a new tensor with the same dimensions where each scalar value is the element-wise subtraction of the scalars in the parent tensors.

$C = A-B$

In [0]:
# subtract tensors
C = A - B
print(C)

#### c) tensor Hadamard product

* The element-wise multiplication of one tensor with another tensor with the same dimensions results in a new tensor with the same dimensions where each scalar value is the element-wise multiplication of the scalars in the parent tensors;

* The Hadamard product is different from tensor multiplication (product), and it is represented by the operator $\circ$

$C = A \circ B$

In [0]:
# multiply tensors
C = A * B
print(C)

#### d) tensor division

* The element-wise division of one tensor with another tensor with the same dimensions results in a new tensor with the same dimensions where each scalar value is the element-wise division of the scalars in the parent tensors;

$C = \frac{A}{B}$

In [0]:
# divide tensors
C = A / B
print(C)

#### e) tensor product

* Given a tensor $A$ with $q$ dimensions and tensor $B$ with $r$ dimensions, the product of theses tensors will be a new tensor with the order of $q + r$ dimensions;

$C = A \otimes B$

$ A = \begin{pmatrix}
       a_{1,1} \space a_{1,2} \\
       a_{2,1} \space a_{2,2} \end{pmatrix}$

$ B = \begin{pmatrix}
       b_{1,1} \space b_{1,2} \\
       b_{2,1} \space b_{2,2} \end{pmatrix}$

$ C = \begin{pmatrix}
       a_{1,1} \times b_{1,1} \space a_{1,1} \times b_{1,2} \space a_{1,2} \times b_{1,1} \space a_{1,2} \times b_{1,2} \\
       a_{1,1} \times b_{2,1} \space a_{1,1} \times b_{2,2} \space a_{1,2} \times b_{2,1} \space a_{1,2} \times b_{2,2} \\
       a_{2,1} \times b_{1,1} \space a_{2,1} \times b_{1,2} \space a_{2,2} \times b_{1,1} \space a_{2,2} \times b_{1,2} \\ a_{2,1} \times b_{2,1} \space a_{2,1} \times b_{2,2} \space a_{2,2} \times b_{2,1} \space a_{2,2} \times b_{2,2} \end{pmatrix}$

* The tensor product in numpy is the `tensordot()` function. The function takes as arguments the two tensors to be multiplied and the axis on which to sum the products over (*sum reduction*);

* To calculate the tensor product (tensor dot product in numpy), the axis must be set to 0;

* In the example, we define two order-1 tensors (vectors) with and calculate the tensor product:

In [0]:
# define first vector
A = np.array([1,2])
# define second vector
B = np.array([3,4])
# calculate tensor product
C = np.tensordot(A, B, axes=0)
print(C)

* The tensor product is the most common form of tensor multiplication, but there are many other types of tensor multiplications that exist, such as the **tensor dot product** and the **tensor contraction**.

---

## Chapter 14 - Matrix decomposition

* Also call **matrix factorization methods**, are methods that reduce a matrix into constituent parts that make it easier to calculate more complex matrix operations;
> It's a way of reducing a matrix into its constituent parts.

* There a range of different matrix decomposition techniques:

### 1. LU decomposition

* It's for square matrices and decomposes a matrix into $L$ and $U$ components;

$A = L \cdot U$

> Where $A$ is the square matrix that we wish to decompose, $L$ is the lower triangle matrix and $U$ is the upper triangle matrix.

* The LU decomposition is found using an iterative numerical process and can fail for those matrices that cannot be decomposed or decomposed easily;

* A variation of this decomposition is numerically more stable to solve in practice is call LU decomposition with partial pivoting (LUP);

$A = L \cdot U \cdot P$

* The rows of the parent matrix are re-ordered to simplify the decomposition process and the additional P matrix specifies a way to permute the result or return the result to the original order;

* The LU decomposition is often used to simplify the solving of systems of linear equations;
> e.g.: Finding the coefficients in a linear regression, as well as in calculation the determinant and inverse of a matrix.

* The LU decomposition can be implemented in Python with the `lu()` function, this function calculates an LPU decomposition.


In [0]:
import scipy
# LUP decomposition
A = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

# Factorize
P,L,U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)
print()
# Reconstruct
B = P.dot(L).dot(U)
print(B)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### 2. QR decomposition

* Is for $n \times m$ matrices (not limited to square matrices) and decomposes a matrix into $Q$ and $R$ components;

$A = Q \cdot R$

> Where $A$ is the matrix that we wish to decompose, $Q$ a matrix with the size $m\times m$, and $R$ is an upper triangle matrix with the size $m \times n$.

* QR decomposition is found using an iterative numerical method that can fail for those matrices that cannot be decomposed, or decomposed easily. Like the LU decomposition, it is often used to solve systems of linear equations, although is not limited to square matrices;

* It can be implemented in Numpy using the `qr()` function, by default the fuction returns the $Q$ and $R$ matrices with smaller or reduced dimensions that is more economical. We can change this to return the expected sizes of $m \times m$ for $Q$ and $m \times n$ for $R$ by specifying the mode argument as `complete`, but not required for most applications.

In [0]:
# QR decomposition
A = np.array([
[1, 2],
[3, 4],
[5, 6]])

# Factorize
Q, R = np.linalg.qr(A, "complete")
print(Q)
print(R)
print()

# Reconstruct
B = Q.dot(R)
print(B)

[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]

[[1. 2.]
 [3. 4.]
 [5. 6.]]


### 3. Cholesky decomposition

* It's for square symmetric matrices where all values are greater than zero, so-called **positive definite matrices**;
> We'll focus on the Cholesky decomposition for real-valued matrices and ignore the cases when working with complex numbers.

$A = L \cdot L^T$

> Where $A$ is the matrix being decomposed, $L$ is the lower triangular matrix and $L^T$ is the transpose of $L$.

* The decompose can also be written as the product of the upper triangular matrix:

$A = U^T \cdot U$

> Where $U$ is the upper triangular matrix.

* The Cholesky decomposition is used for solving linear least squares for linear regression, as well as simulation and optimization methods;

* When decomposing symmetric matrices, the Cholesky decomposition is nearly twice as efficient as the LU decomposition and should be preferred in these cases;

* In Numpy we can use the `cholesky()` function, it returns $L$ as we can easily access the $L$ transpose as needed.

In [0]:
# Cholesky decomposition
A = np.array([
[2, 1, 1],
[1, 2, 1],
[1, 1, 2]])

# Factorize
L = np.linalg.cholesky(A)
print(L)
print()

# Reconstruct
B = L.dot(L.T)
print(B)

[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


---
## Chapter 15 - Eigendecomposition

* It decomposes a matrix into eigenvectors and eigenvalues;
> Uder in the principal component analysis (PCA) method.

### Eigendecomposition of a matrix

* Involves decomposing a square matrix into a set of eigenvectors and eigenvalues;

* A vector is an eigenvector of a matrix if it satisfies the eigenvalue equation:

$A.v = \lambda.v$

> Where $A$ is the parent square matrix that we're decomposing, $v$ is the eigenvector of the matrix, and $\lambda$ represents the eigenvalue scalar.

* A matrix could have one eigenvector and eigenvalue for each dimension of the parent matrix;

* Not all square matrices can be decomposed into eigenvectors and eigenvalues, and some can only be decomposed in a way that requires complex numbers;

* The parent matrix can be show to be a product of the eigenvectors and eigenvalues;

$A = Q.\Lambda.Q^T$

> Where $Q$ is a matrix comprised of the eigenvectors, $\Lambda$ is the diagonal matrix comprised of the eigenvalues, and $Q^T$ is the transpose of the matrix comprises of the eigenvectors.

* A decomposition operation does not result in a compression of the matrix. Instead, it breaks it down into constituent parts to make certain operations on the matrix easier to perform;

* Eigendecomposition is used as an element to simpligy the calculation of other more complex matrix operations;

* Almost all vectors change direction, when they are multiplied by $A$. Certain exceptional vectors $x$ are in the same direction as $Ax$. Those are the "eigenvectors";

* Multiply an eigenvector by $A$, and the vector $Ax$ is the number $\lambda$ times the original $x$;

* The eigenvalue $\lambda$ tells whether the special vector $x$ is stretched or shrunk or reversed or left unchanged, when it is multiplied by $A$.

### Eigenvectors and eigenvalues

* Eigenvectors (right vectors) are unit vectors, which means that their length or magnitude is equal to 1.0;

* Eigenvalues are coeficients applied to eigenvectors that give the vectors their length or magnitude;
> For example, a negative eigenvalue may reverse the direction of the eigenvector as part of scaling it.

* A matrix that has only positive eigenvalues is referred to as a **positive definite matrix**, whereas if the eigenvalues are all negative, it is referred to as a **negative definite matrix**.

### Calculation of eigendecomposition

* An eigendecomposition is calculated on a square matrix using an efficient iterative algorithm;

* Often an eigenvalue is found first, then an eigenvector is found to solve the equation as a set of coefficients;

* The eigendecomposition can be calculated in NumPy using the `eig()`function.

In [1]:
import numpy as np

# eigendecomposition
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
print(A)
print()

# factorize
values, vectors = np.linalg.eig(A)
print(values)
print(vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


### Confirm an eigenvector and eigenvalue

* To confirm that a vector is a eigenvector we multiply it by the value and comparing the result with the eigenvalue;

* Define a matrix, then calculate the eigenvalues and eigenvectors, then test whether the first vector and value are in fact an eigenvalue and eigenvector for the matrix;

In [2]:
B = A.dot(vectors[:, 0])
print(B)
print()

C = vectors[:, 0] * values[0]
print(C)

[ -3.73863537  -8.46653421 -13.19443305]

[ -3.73863537  -8.46653421 -13.19443305]


* The eigenvectors are returned as a matrix with the same dimensions as the parent matrix, where each column is an eigenvector;
> e.g. the first eigenvector is `vector[:,0]`.

* Eigenvalues are returned as a list, where value indices in the returned array are paired with eigenvectors by column index.
> e.g. the first eigenvalue at `values[0]` is paired with the first eigenvector at `vectors[:, 0]`.

* The example multiplies the original matrix with the first eigenvector and compares it to the first eigenvector multiplied by the first eigenvalue.

### Reconstruct matrix

* First, the list of eigenvectors must be taken together as a matrix, where each vector becomes a row;

* The eigenvalues need to be arraged into a diagonal matrix (`diag()`), then we need the inverse of the eigenvector matrix (`inv()`) and finally multiply together using the `dot()` function.

In [3]:
# create a matrix from eigenvectors
Q = vectors

# create inverse of eigenvectors matrix
R = np.linalg.inv(Q)

# create diagonal matrix from eigenvalues
L = np.diag(values)

# reconstruct the original matrix
B = Q.dot(L).dot(R)
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


---

## Chapter 16 - Singular value decomposition (SVD)

* All matrices have an SVD, which makes it more stable than other methods, such as the eigendecomposition;
> It is often used in compressing, denoising, data reduction, etc.

### What is the SVD

* Is a matrix decomposition method for reducing a matrix to its constituent parts in order to make certain subsequent matrix calculations simpler;

* Let's focus on the SVD for **real-valued matrices**, ignoring the complex numbers case;

$A = U.\Sigma.V^T$

> Where $A$ is the real $n \times m$ matrix that we wish to decompose, $U$ is an $m \times m$ matrix, $\Sigma$ is an $m \times n$ diagonal matrix, and $V^T$ is the $V$ transpose of an $n \times n$ matrix.

* The diagonal values in the $\Sigma$ matrix are known as the **singular values** of the original matrix $A$. The columns of the $U$ matrix are called the **left-singular vectors** of $A$ and the columns of $V$ are called the **right-singular vectors** of $A$;

* The SVD is calculated via iterative numerical methods (without details). Every rectangular matrix has a singular value decomposition, although the resulting matrices may contain complex numbers and the limitations of floating point arithmetic may cause some matrices to fail to decompose neatly;

* The SVD allows to discover some of the same kind of information as the eigendecomposition been generally applicable;
> Examples are the calculation of matrix inverse, data reduction, least squares linear regression, imag compression, and denoising data.

### Calculate SVD

* In NumPy the `svd()` function takes a matrix and returns the $U$, $\Sigma$ and $V^T$ elements;

 - The $\Sigma$ diagonal matrix is returned as a vector of singular values;

 - The $V$ matrix is returned in a transposed form ($V^T$).

In [4]:
import numpy as np

# singular-value decomposition
A = np.array([
    [1,2],
    [3,4],
    [5,6]
])
print(A)
print()

# factorize
U, s, V = np.linalg.svd(A)
print(U)
print(s)
print(V)

[[1 2]
 [3 4]
 [5 6]]

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


### Reconstruct matrix

* We use the $U$, $\Sigma$ and $V^T$ returned from `svd()` function, but they cannot be multiplied directly;

* The vector `s` must be converted into a diagonal matrix (`diag()`, create a square matrix $m \times m$ relative to the original matrix), which is a problem as the size of the matrix do not fit the rules of matrix multiplication (number tof columns in a matrix equal the number of rows of the subsequent matrix);

* After creating the square $\Sigma$ diagonal matrix, the sizes of the matrices are relative to the original $n \times m$ matrix:

$U(m \times m) \cdot \Sigma(m \times m) \cdot V^T(n \times n)$

But we require:

$U(m \times m) \cdot \Sigma(m \times n) \cdot V^T(n \times n)$

* We can achieve this by creating a new $\Sigma$ matrix of all zero values that is $m \times n$ (e.g. more rows) and populate the first $n \times n$ of the matrix with the square diagonal matrix calculated via `diag()`. 

In [5]:
# reconstruct rectangular matrix from SVD
# create m x n Sigma matrix
sigma = np.zeros((A.shape[0], A.shape[1]))

# populate Sigma with n x n diagonal matrix
sigma[:A.shape[1], :A.shape[1]] = np.diag(s)

# reconstruct matrix
B = U.dot(sigma.dot(V))
print(B)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


* The above complication with the $\Sigma$ diagonal only exists with the case where $m$ and $n$ are different. The diagonal matrix can be used directly when reconstructing a square matrix.

In [6]:
# reconstruct square matrix from SVD
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(A)
print()

# factorize
U,s,V = np.linalg.svd(A)

# create n x n Sigma matrix
sigma = np.diag(s)

# reconstruct matrix
B = U.dot(sigma.dot(V))
print(B)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Pseudoinverse (Moore-Penrose inverse)

* Is the generalization of the matrix inverse for square matrices to rectangular matrices where the number of rows and columns are not equal;

$A^+ = V\cdot D^+ \cdot U^T$

> Where $A^+$ is the pseudoinverse, $D^+$ is the pseudoinverse of the diagonal matrix $\Sigma$ and $V^T$ is the transpose of $V^T$. We can get $U$ and $V$ from SVD operation.

$A = U \cdot \Sigma \cdot V^T$

* The $D^+$ can be calculated by creating a diagonal matrix from $\Sigma$, calculation the reciprocal of each non-zero element in $\Sigma$ and taking the transpose if the original matrix was retangular;

$\Sigma = \begin{pmatrix}
       s_{1,1} \space 0 \space 0 \\
       0 \space s_{2,2} \space 0 \\
       0 \space 0 \space s_{3,3} \end{pmatrix}$

$D^+ = \begin{pmatrix}
       \frac{1}{s_{1,1}} \space 0 \space 0 \\
       0 \space \frac{1}{s_{2,2}} \space 0 \\
       0 \space 0 \space \frac{1}{s_{3,3}} \end{pmatrix}$

* The pseudoinverse provides one way of solving the linear regression equation, specifically when there are more rows than columns (the often case);


* NumPy provides the `pinv()` function for calculation the pseudoinverse of a rectangular matrix.

In [7]:
# pseudoinverse

A = np.array([
    [.1, .2],
    [.3, .4],
    [.5, .6],
    [.7, .8]
])
print(A)
print()

# calculate pseudoinverse
B = np.linalg.pinv(A)
print(B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]

[[-1.00000000e+01 -5.00000000e+00  1.42385628e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


* We can calculate the pseudoinverse manually via SVD and compare the results to the `pinv()` function;

* First we must calculate the SVD, next the reciprocal of each value in the `s` array. Then the `s` array can be transformed into a diagonal matrix with an added row of zeros to make it rectangular. Finally, we can calculate the pseudoinverser from the elements:

$A^+ = V^T \cdot D^T \cdot U^T$

In [8]:
# pseudoinverse via svd
# factorize
U,s,V = np.linalg.svd(A)

# reciprocals of s
d = 1.0 / s

# create m x n D matrix
D = np.zeros(A.shape)

# populate D with n x n diagonal matrix
D[:A.shape[1], :A.shape[1]] = np.diag(d)

# calculate pseudoinverse
B = V.T.dot(D.T).dot(U.T)
print(B)

[[-1.00000000e+01 -5.00000000e+00  1.42578328e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


### Dimensionality reduction

* Data with a large number of features, such as more features (columns) than observations (row) may be reduced to a smaller subset of features that are most relevant to the prediction problem;

* The result is a matrix with a lower rank that is said to approximate the original matrix;

* We can perform a SVD operation on the original data and select the top %k% largest singular values in $\Sigma$. These columns can be selected from $\Sigma$ and the rows selected from $V^T$. An approximate $B$ of the original vector $A$ can be reconstructed;

$B = U \cdot \Sigma_k \cdot V_k^T$

* In natural language processing (NLP), this approach can be used on matrices of word occurrences or word frequencies in documents and is called **Latent Semantic Analysis** or **Latent Semantic Indexing**.
> In practice, we can retain and work with a descriptive subset of the data called $T$:

$T = U \cdot \Sigma_k$

* Further, this transform can be calculated and applied to the original matrix $A$ as well as other similar matrices:

$T = A \cdot V^T_k$



In [9]:
# data reduction with svd

A = np.array([
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30]
])
print(A)
print()

# factorize
U,s,V = np.linalg.svd(A)

# create m x n Sigma matrix
sigma = np.zeros((A.shape[0], A.shape[1]))

# populate Sigma with n x n diagonal matrix
sigma[:A.shape[0], :A.shape[0]] = np.diag(s)

# select

n_elements = 2
sigma = sigma[:, :n_elements]
V = V[:n_elements, :]

# reconstruct
B = U.dot(sigma.dot(V))
print(B)
print()

#transform
T = U.dot(sigma)
print(T)
T = A.dot(V.T)
print(T)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]

[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


* The SVD is calculated and only the first two features are selected. The elements are recombined to give an accurate reproduction of the original matrix and the transform is calculated in two different ways;

* The scikit-learn provides a `TruncatedSVD` class that implements this capability directly. This class can be created in which you must specify the number of desirable features or components to select. Once created, you can fit the transform (e.g calculate $V_k^T$) by calling `fit()` function, then apply it to the original matrix by calling the `transform()`function.

In [11]:
# svd data reduction in scikit-learn
from sklearn.decomposition import TruncatedSVD

# create transform
svd = TruncatedSVD(n_components=2)

# fit transform
svd.fit(A)

# apply transform
result = svd.transform(A)
print(result)

[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]


* Except for the sign on some values, the result is the same as calculated manually above. We can expect there to be some instability when it comes to the sigh given the nature of the calculations involved and the differences in the underlying libraries and methods used.
> This instability of sign should not be a problem in practice as long as the transform is trained to reuse.

---

## Part VI - Statistics

### Chapter 17 - Introduction to multivariate statistics

